[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://69.62.79.202:9001/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
